# action.yml
name: "thereisnotime/action-sqlmap"
description: "Run sqlmap in your GitHub Actions workflow"

inputs:
  url:
    description: "Target URL (e.g. http://www.blackfox-security.com/vuln.php?id=1)"
    required: true
    default: ""
  additional_args:
    description: "Additional arguments to pass to sqlmap. Default is --batch to run in non-interactive mode."
    required: false
    default: "--batch"

runs:
  using: "docker"
  image: "Dockerfile"
  options: "--network web" 
  entrypoint: /bin/sh
  args:
    - -c
    - |
      args="--url=${{ inputs.url }}"
      additional_args="${{ inputs.additional_args }}"
      set -- $additional_args
      for arg do
        args="$args $arg"
      done
      echo $args
      exec /usr/local/bin/python3 /sqlmap/sqlmap.py $args

branding:
  icon: "map"
  color: "red"
